---
title: "Problem Set 03"
subtite: "TEMPLATE"
output: 
  html_document:
    toc: true
    toc_float: true
    number_section: false
    highlight: tango
    theme: "cosmo"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```

## Exercise 1

## Exercise 2

## Exercise 3

## Exercise 4

a)

b)

c)

d)

## Exercise 5

a)

b)

c) 


## Exercise 6

*List which scenarios (A - E) are PAIRED*

## Exercise 7

```{r}
# create data

```

a) 

b) 

c) 

```{r}
# compute point estimate
```

d) 

```{r}
# compute confidence interval
```

e) 

f)

## Exercise 8

```{r}
# create data

```

a) 

b) 

c) 

```{r}
# compute point estimate
```


d) 

```{r}
# compute confidence interval
```

e) 

f)

## Exercise 9

```{r}
# create data

```

a) 

b) 

c) 

```{r}
# compute point estimate
```

d) 

```{r}
# compute confidence interval
```

e) 

f)



## Exercise 10

```{r}
# create data

```

a) 

b) 

c) 

```{r}
# compute point estimate
```


d) 

```{r}
# compute confidence interval
```

e) 

f)

## Exericse 11

```{r}
# create data

```

a) 

b) 

c) 

```{r}
# compute point estimate
```

d) 

```{r}
# compute confidence interval
```

e) 

f)

## Exercise 12

```{r}
# create data

```

a) 

b) 

c) 

```{r}
# compute point estimate
```

d) 

```{r}
# compute confidence interval
```

e) 

f)

## Exercise 13

```{r}
# create data

```

a) 

b) 

c) 

```{r}
# compute point estimate
```

d) 

```{r}
# compute confidence interval
```

e) 

f)