---
title: "Week 02 Day 01"
#subtitle: "Knowledge Check"
output: 
  html_document:
    toc: true
    toc_float: true
    number_section: false
    highlight: tango
    theme: "cosmo"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

## Reading Annotation Q/A

1. Where does $\alpha$ come from, why is it over 2?

2. When $X_1, X_2, ... X_n \sim N(\mu, \sigma^2),$ then $\bar{X} \sim N(\mu, \frac{\sigma^2}{n})$ and CI is given by $\bar{X} \pm z_{\alpha/2}\frac{\sigma}{\sqrt{n}}$. Is normality assumption necessary here? Doesn't CLT tell us this is true even if underlying distribution is not Normal? 

3. Why would we ever use the method above, when it requires that $\sigma^2$ is known, and that's unrealistic? Would we ever know $\sigma^2$?

4. WON'T BE USING MINITAB - feel free to skip those sections :)

5. Book: "In reality we only take one random sample". Student: "Is one sample enough to test if an interval is correct or incorrect? If so, why only one when usually we take so many samples?" 

6. "This reminds me of the two different types of errors, which I am sure we will review later in this class because type 1 and type 2 errors can give some insight into our possible incorrectness. I find it troubling despite our use of statistics to find an unknown, the correctness of our answer can still be unknown. Whenever I use confidence intervals in research, I tend to struggle with determining confidence percentage to ensure a higher likeliness that my resulting interval contains the population mean"

7. Its necessary to find the balance between efficiency and accuracy. How can we determine the largest sample "we can afford"? 

8. How large is large enough? $n \geq 30$ if not skewed, but what about when data is skewed? 

## Knowledge Check

1. How is $\overline{X}$ distributed? What conditions does this depend on? 
1. How is $\frac{\overline{X} - \mu}{\sigma/\sqrt{n}}$ distributed? What symbol do we use for this expression?

1. Draw a picture that illustrates what $z_{\alpha/2}$ stands for.

1. Why is it incorrect to say "The probability $\mu$ falls between L (lower bound) and U (upper bound) is $1-\alpha$"?

1. What percentage of 80% confidence intervals will "fail"? What does it mean to fail? 

1. What is the difference between $\overline{X}$ and $\mu$? 

1. What does $s$ mean? How does it differ from $\sigma$? 

1. When should we use the t-distribution? Why? 

1. How is $\frac{\overline{X} - \mu}{s/\sqrt{n}}$ distributed? What symbol do we use for this expression?

1. How many *parameters* does the normal distribution have? What are they called/how are they denoted? What about the t-distribution? 

1. What is the difference between a point estimate and a parameter? Give three examples of point estimates and their corresponding parameters. 

1. What is the difference between standard deviation, standard error, and margin of error? How are they related to one another? 

1. Explain the notation $t_{\alpha/2, n-1}$. Draw a picture to illustrate it. 

