---
title: "Week 08 Day 02"
subtitle: ""
output: 
  html_document:
    toc: true
    toc_float: true
    number_section: false
    highlight: tango
    theme: "cosmo"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```

## Student Questions

+ Book: "Because we know that if the correlation coefficient is 0, then $X$ and $Y$ are independent random variables"
    + You're correct that this is wrong! 
+ What is MSE and what does it do?

$$MSE = \frac{\sum_{i = 1}^n (Y_i - \hat{Y}_i)^2}{n-2}$$

+ Why does the test statistic have $n-2$ degrees of freedom instead of $n-1$
$$T = \frac{\hat{\beta} - \beta}{\sqrt{\frac{MSE}{\sum(x_i - \bar{x})^2}}}$$

+ Why is that ^^ the test statistic?
+ Why would we want to test $H_0: \beta = \beta_0$
+ What R code do we use to get the regression/hypothesis test output?

## PS 08 - work on the board!

## Knowledge Check

+ What does each symbol in the following formula mean? 
$$Y_i = \alpha + \beta(x_i - \bar{x}) + \epsilon_i$$
+ Which of the above are the parameters of interest?
+ What is the traditional assumption for how $\epsilon_i$ is distributed? What does this imply about the distribution of $Y_i$?
+ Write out the hypotheses for testing the slope parameter.
+ What is the distribution of $\frac{\hat{\beta} - \beta}{\sqrt{\frac{MSE}{\sum_{i=1}^n(x_i - \bar{x})^2}}}$? Include degrees of freedom.
+ What code would you use to find an appropriate critical value for the above test statistic?
+ What code would you use to find the p-value for the above test statistic?
+ How do you conduct a hypothesis test for a slope in R? 



